# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Core CI

on:
  push:
    branches: ["master", "main"]
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  ci_core_p1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

      - name: Install dependencies
        run: |
          ls -l
          go get .

      - name: Run unit tests
        run: |
          go test .
